### PR TITLE
Let each PoW impl. benchmark the same tx and mwm

### PR DESCRIPTION
**Pull request by chenwei-tw**

### CODE REVIEW

**Comment by knarz** [comment]
Maybe just make that tx a variable so it's a bit easier to change in the future?

**Comment by maeck70** [comment]
I believe the different PoW types do test in different ways. Pow_Go and Pow_C only do a single test, whereas, Pow_SSE, Pow_C128 and others do multiple parallel tests.

**Comment by chenwei-tw** [comment]
I think PoW needs more trytes for evaluation of each implementation, because different trytes give different performance.

For example, here is evaluation between SSE and AVX with 6000 trytes. (each sample measured elapsed time with 30 trytes, total 200 samples)


At least, I think a consistent tryte for each implementation is needed.

**Comment by maeck70** [comment]
How are you suggesting we do that. Just cycle through an array of 30 Trytes of which the hash ends with '99999'?

**Comment by luca-moser** [comment]
This changes are not compatible anymore with the refactored iota.go library. Please consider opening a new PR with your wanted changes. All tests in the refactored library use the same mwm.

**Pull request closed without merging**
